### ISSUE TITLE
Handle drone Crash

### ISSUE THREAD

**Issue by marcoff181** [The-Null-Pointer-Patrol/null-pointer-drone#14]
From what I understood in the WG today:
- crash message arrives
- drone enters a "special state" in which it:
   - normally processes received messages
   - if the receiver is empty does nothing
   - if the receiver returns an [error](https://docs.rs/crossbeam/latest/crossbeam/channel/struct.RecvError.html#impl-Display-for-RecvError) it means that all the neighbors disconnected and it can go on with the next step
- there are no more messages to process because the receiver was empty and disconnected, close its thread

**Comment by marcoff181** [comment]
See https://github.com/WGL-2024/WGL_repo_2024/pull/108 for more details when it gets completed

**Comment by di-bon** [comment]
Solved by #21
