### ISSUE TITLE
Possible bug in nack routing when there is no valid neighbors

### ISSUE THREAD

**Issue by jarkko793** [The-Null-Pointer-Patrol/null-pointer-drone#37]
According to the [protocol line 340](https://github.com/WGL-2024/WGL_repo_2024/blob/f88f1f263ba5e0d356bac60b694f787bcc8c7107/AP-protocol.md?plain=1#L340):

> 	- **If `next_hop` is not a neighbor** of the drone, send a Nack with `ErrorInRouting` (including the problematic `NodeId` of `next_hop`) and terminate processing. 

It seems that we are panicking in this case, and not returning `nack`.

Let's say that we have a drone with id `0`, and it has a neighbor `1`. Now, if we have a `SourceRoutingHeader` of `0,3,2,4,5` with `hop_index` of `0`, the drone will create `nack`, but when it loops back to `send_packet` method to send the created `nack` it will panic since the newly constructed `SourceRoutingHeader` will have `hop_index` of `1` while the `hops` vector is `[0]`.

Still need to verify the bug and also make sure that there is no user error here.

**Comment by marcoff181** [comment]
But that source routing header is invalid, it has no sender because the first element is the drone itself.

I think we should check in process-not-fragment that case(hop index is 0, which should never happen) as a reason to panic (not sure if it is caught by the other checks, dont think so)

**Comment by marcoff181** [comment]
Like, maybe the protocol isnt explicit about that, but in that case, there is no sender because hop_index is 0, so it needs to be rejected by the drone, otherwise it breaks the logic as you show.

So I say lets add a panic for that, document it in the readme and add a todo to add a test for that edge case.

If you can find other problematic packets with hop-idx >= 1 then that's another whole problem : )

**Comment by jarkko793** [comment]
> But that source routing header is invalid

Ah, yes you are right. Reused code snippets from other tests and here we are.

> If you can find other problematic packets with hop-idx >= 1 then that's another whole problem : )

Very true :D

**Comment by marcoff181** [comment]
> Ah, yes you are right. Reused code snippets from other tests and here we are.

A great excuse to add yet another panic : )

so to close this issue we need to:
- [x] add the check and panic
- [x] add a test

Probably we can do this after the fair?

**Comment by jarkko793** [comment]
> Probably we can do this after the fair?

Agreed
