### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by marcoff181** [The-Null-Pointer-Patrol/null-pointer-drone#4]
have a way for people that bought the drone to ask for help(even just telling them to open an issue)

**Comment by saussice9** [comment]
I think I can do this task. I just have to describe all the functions users can use

**Comment by marcoff181** [comment]
#31 adds some sections

**Comment by marcoff181** [comment]
Still missing the section that tells people to open an issue if they are having problems with our drone

**Comment by jarkko793** [comment]
I suppose the issue can be closed?
